[profile.default]
solc_version = "0.8.28"
evm_version = "cancun"

optimizer = true
optimizer_runs = 9_999_999

remappings = [
  "@solady=lib/solady/",
  "@forge=lib/forge-std/src/"
]

[profile.via-ir]
via_ir = true

[fmt]
line_length = 100